### ISSUE TITLE
[Question] Game Shop part1 에서 Item 생성자에 인자가 있는 이유를 모르겠습니다.

### ISSUE THREAD

**Issue by Kinter** [utilForever/ProgrammingPractice#1]
문서를 보면
Item(name, description, weight, value) : 매개 변수로 아이템 이름/설명/무게/가격을 받는 생성자
이렇게 되어 있는데, 위 식대로 그대로 하면 문법에 맞지 않은거 같은데,
굳이 저대로 생성자 안만들고 저런 식으로 하라고 써 놓으신 건가요??
 아니면 제가 틀린 건가요??

**Comment by utilForever** [comment]
질문을 제대로 이해를 못했는데, 문법에 맞지 않는다는게 무슨 소리신지 잘 모르겠네요.
언어마다 문법은 다를 수 있습니다. 제가 C++을 생각해서 저렇게 써놓지 않았나 싶은데,
언어에 따라서는 저대로 안만들고 비슷한 방식으로 구현하시면 되겠습니다.

**Comment by Kinter** [comment]
C++ 클래스 내에서
```C++
Item(name, description, weight, value);
```
를 입력했을 때 컴파일이 안되서 문법에 맞지 않다는 표현을 했습니다. 일단 의미는 이해를 했네요. 감사합니다.
